// <auto-generated />
using System;
using GreenClaimsGuard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenClaimsGuard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929135512_AddProductDetailsToComplianceReview")]
    partial class AddProductDetailsToComplianceReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.AnalysisLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiExplanation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_explanation");

                    b.Property<int?>("ComplianceScore")
                        .HasColumnType("int")
                        .HasColumnName("compliance_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GroupedFindingsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("grouped_findings_json");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("input_text");

                    b.Property<string>("OverallRisk")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("overall_risk");

                    b.Property<string>("RuleFindingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rule_findings_json");

                    b.Property<string>("SuggestedRewrite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("suggested_rewrite");

                    b.Property<int?>("TotalIssues")
                        .HasColumnType("int")
                        .HasColumnName("total_issues");

                    b.Property<string>("TrafficLight")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("traffic_light");

                    b.HasKey("Id");

                    b.ToTable("analysis_logs", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.ComplianceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AiStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ai_status");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DecisionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("decisions_json");

                    b.Property<string>("FinalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("final_description");

                    b.Property<string>("LegacyProductKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("legacy_product_key");

                    b.Property<string>("Market")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("market");

                    b.Property<bool>("NeedsOverride")
                        .HasColumnType("bit")
                        .HasColumnName("needs_override");

                    b.Property<int?>("OpenIssueCount")
                        .HasColumnType("int")
                        .HasColumnName("open_issue_count");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("overall_status");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("override_reason");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("RulesVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("rules_version");

                    b.Property<string>("SendBackComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("send_back_comment");

                    b.Property<string>("SendBackReason")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("send_back_reason");

                    b.Property<string>("Subcategory")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("subcategory");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("tags");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("validation_json");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CreatedAt");

                    b.ToTable("compliance_reviews", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.PublicClaimSeedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baseline")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("baseline");

                    b.Property<DateTime>("CapturedDate")
                        .HasColumnType("date")
                        .HasColumnName("captured_date");

                    b.Property<string>("ClaimSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_sentence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EvidenceReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evidence_reference");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("issue_type");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("product_id");

                    b.Property<double?>("ReductionPercentage")
                        .HasColumnType("float")
                        .HasColumnName("reduction_percentage");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("source_title");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("source_url");

                    b.Property<string>("Timeframe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("timeframe");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("public_claims_seed", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("action");

                    b.Property<string>("AiStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("ai_status");

                    b.Property<string>("CopyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("copy_hash")
                        .IsFixedLength();

                    b.Property<string>("CopySnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("copy_snapshot");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issues_json");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justification");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("market");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("RulesStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("rules_status");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("rules_version");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ProductId", "Timestamp");

                    b.ToTable("audit_ledger", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.FactsRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("requested_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CreatedAt");

                    b.ToTable("facts_requests", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("FactsVerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("facts_verified_at");

                    b.Property<string>("FactsVerifiedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("facts_verified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("origin");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.ProductCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_certifications", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.ProductDraft", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("market");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("saved_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("ProductId");

                    b.HasIndex("SavedAt");

                    b.ToTable("product_drafts", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.ProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("material");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentage");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_materials", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.UserDirectoryEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen_at");

                    b.HasKey("UserId");

                    b.ToTable("user_directory", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.ComplianceReview", b =>
                {
                    b.HasOne("GreenClaimsGuard.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.AuditEntry", b =>
                {
                    b.HasOne("GreenClaimsGuard.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.FactsRequest", b =>
                {
                    b.HasOne("GreenClaimsGuard.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.ProductCertification", b =>
                {
                    b.HasOne("GreenClaimsGuard.Api.Models.Product", null)
                        .WithMany("Certifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.ProductDraft", b =>
                {
                    b.HasOne("GreenClaimsGuard.Api.Models.Product", "Product")
                        .WithOne()
                        .HasForeignKey("GreenClaimsGuard.Api.Models.ProductDraft", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.ProductMaterial", b =>
                {
                    b.HasOne("GreenClaimsGuard.Api.Models.Product", null)
                        .WithMany("Materials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.Product", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
