// <auto-generated />
using System;
using GreenClaimsGuard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenClaimsGuard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924164815_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.AnalysisLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiExplanation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_explanation");

                    b.Property<int?>("ComplianceScore")
                        .HasColumnType("int")
                        .HasColumnName("compliance_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GroupedFindingsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("grouped_findings_json");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("input_text");

                    b.Property<string>("OverallRisk")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("overall_risk");

                    b.Property<string>("RuleFindingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rule_findings_json");

                    b.Property<string>("SuggestedRewrite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("suggested_rewrite");

                    b.Property<int?>("TotalIssues")
                        .HasColumnType("int")
                        .HasColumnName("total_issues");

                    b.Property<string>("TrafficLight")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("traffic_light");

                    b.HasKey("Id");

                    b.ToTable("analysis_logs", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.ComplianceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DecisionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("decisions_json");

                    b.Property<string>("FinalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("final_description");

                    b.Property<string>("LegacyProductKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("legacy_product_key");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("overall_status");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("validation_json");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CreatedAt");

                    b.ToTable("compliance_reviews", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.GreenClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Claim");

                    b.Property<string>("GptRewrite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GptRewrite");

                    b.HasKey("Id");

                    b.ToTable("GreenClaims", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.PublicClaimSeedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baseline")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("baseline");

                    b.Property<DateTime>("CapturedDate")
                        .HasColumnType("date")
                        .HasColumnName("captured_date");

                    b.Property<string>("ClaimSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_sentence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EvidenceReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evidence_reference");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("issue_type");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("product_id");

                    b.Property<double?>("ReductionPercentage")
                        .HasColumnType("float")
                        .HasColumnName("reduction_percentage");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("source_title");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("source_url");

                    b.Property<string>("Timeframe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("timeframe");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("public_claims_seed", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("GreenClaimsGuard.Api.Data.ComplianceReview", b =>
                {
                    b.HasOne("GreenClaimsGuard.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
